ARTIFACT = u"Artifact"
CREATURE = u"Creature"
ENCHANTMENT = u"Enchantment"
LAND = u"Land"
PLANESWALKER = u"Planeswalker"

INSTANT = u"Instant"
SORCERY = u"Sorcery"

PERMANENTS = {ARTIFACT, CREATURE, ENCHANTMENT, LAND, PLANESWALKER}
NONPERMANENTS = {INSTANT, SORCERY}
TYPES = PERMANENTS | NONPERMANENTS


def is_permanent(type):
    return type in PERMANENTS
